#
#  Author: Hari Sekhon
#  Date: 2020-02-16 18:40:53 +0000 (Sun, 16 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                               N a m e s p a c e
# ============================================================================ #

# https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

# https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/

---
apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE # eg. production
