#
#  Author: Hari Sekhon
#  Date: 2020-02-16 18:49:48 +0000 (Sun, 16 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                             R o l e B i n d i n g
# ============================================================================ #

# https://kubernetes.io/docs/reference/access-authn-authz/rbac/

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: NAME
  namespace: NAMESPACE
subjects:
- kind: User
  name: <user@domain.com>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
