#
#  Author: Hari Sekhon
#  Date: 2019-11-27 12:19:45 +0000 (Wed, 27 Nov 2019)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                 V e r t i c a l   P o d   A u t o s c a l e r
# ============================================================================ #

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: APP-vpa
  namespace: NAMESPACE
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: APP-deployment
  updatePolicy:
    updateMode: "auto"
